# fly.toml app configuration file generated for shop-chat-agent-morning-sunset-5014 on 2026-01-04T20:19:24+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shop-chat-agent-encanto-prod'
primary_region = 'ams'

[build]

[env]
  HOST = '0.0.0.0'
  PORT = '3000'
  DATABASE_URL = 'file:/data/dev.sqlite'
  SCOPES = 'customer_read_customers,customer_read_orders,customer_read_store_credit_account_transactions,customer_read_store_credit_accounts,unauthenticated_read_product_listings'
  SHOPIFY_APP_URL = 'https://shop-chat-agent-encanto-prod.fly.dev'

[processes]
  app = 'node ./dbsetup.js npm run docker-start'

[[mounts]]
  source = 'data'
  destination = '/data'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '10GB'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
